kind: pipeline
name: CI

steps:
- name: build
  image: pandry/cppbuildimage
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make
  
- name: tests
  image: pandry/cppbuildimage
  commands:
  - build/bin/unit_tests
