kind: pipeline
name: CI

steps:
- name: build
  image: braintwister/gcc-8
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make
- name: tests
  image: debian:stretch
  commands:
  - build/bin/unit_tests
