version: 2
jobs:
  build:
    docker:
      - image: pandry/cppbuildimage
    steps:
      - checkout
      - run:
          name: Build
          working_directory: ~/project/
          command: |
              mkdir build
              cd build
              cmake ..
              make
      
      - run:
          name: Test
          working_directory: ~/project/build/bin
          command: ./unit_tests
